intertrace/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from recordtrace import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^recordtrace/', include('recordtrace.urls', namespace="recordtrace")),
    url(r'^trace', views.trace, name='trace'),
    url(r'^admin/', include(admin.site.urls)),
    #url('^', include('django.contrib.auth.urls')),
    url(r'^login/$', auth_views.login),
    #url(r'^accounts/logout/$', auth_views.logout),
    # Examples:
    # url(r'^intertrace/', include('intertrace.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
]

recordtrace/urls.py
#from django.conf import settings
#from django.conf.urls.static import static
from django.conf.urls import url

from recordtrace import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^trace$', views.trace, name='trace'),
    url(r'^projects$', views.projects, name='projects'),
    url(r'^temp_projects$', views.temp_projects, name='temp_projects'),
    url(r'^connections/(?P<session_doc_url>\S+)/$', views.connections, name='connections'),
    url(r'^unique_session_table/(?P<session_id>\S+)/$', views.unique_session_table, name='unique_session_table'),
    url(r'^unique_session/(?P<uuid>\S+)/(?P<proj_url>\S+)/$', views.unique_session, name='unique_session'),
    url(r'^session/(?P<uuid>\S+)/$', views.session, name='session'),
    #url(r'^session/(?P<session_id>\d+)/$', views.session, name='session'),
    url(r'^sessionvis/(?P<session_id>\d+)/$', views.sessionvis, name='sessionvis'),
    url(r'^json/(?P<session_id>\d+)/$', views.showJSON, name='json'),
    url(r'^projJSON/(?P<proj_url>\S+)/$', views.showProjJSON, name='projJSON'),
    url(r'^projCSV/(?P<proj_url>\S+)/$', views.showProjCSV, name='projCSV'),
    url(r'^csv/(?P<session_id>\d+)/$', views.showCSV, name='csv'),
    url(r'^sessionJSON/(?P<session_id>\d+)/$', views.sessionJSON, name='sessionJSON'),
    url(r'^sessionVJSON/(?P<uuid>\S+)/$', views.sessionVJSON, name='sessionVJSON'),
    url(r'^projDJSON/(?P<proj_url>\S+)/$', views.projJSON, name='projDJSON'),
    url(r'^projDCSV/(?P<proj_url>\S+)/$', views.projCSV, name='projDCSV'),
    url(r'^downloadCSV/(?P<session_id>\S+)/$', views.downloadCSV, name='downloadCSV'),
    url(r'^downloadFULLCSV/(?P<proj_url>\S+)/$', views.downloadFULLCSV, name='downloadFULLCSV'),
    url(r'^downloadJSON/(?P<session_id>\S+)/$', views.downloadJSON, name='downloadJSON'),
    url(r'^downloadFULLJSON/(?P<proj_url>\S+)/$', views.downloadFULLJSON, name='downloadFULLJSON'),
    url(r'^event/(?P<event_id>\d+)$', views.event, name='event'),
]

recordtrace/models.py
from django.db import models

#import base64


class Session(models.Model):
    session = models.CharField(max_length=200,db_index=True)
    date = models.DateTimeField(auto_now_add=True, db_index=True)
    doc_url = models.CharField(max_length=1024)
    browser = models.CharField(max_length=1024)
    def count_events(self):
        return Event.objects.filter(session = self.id).count()
    def count_people(self):
        return Session.objects.filter(doc_url = self.doc_url).values('session').distinct().count()

class Metadata(models.Model):
    session = models.ForeignKey(Session,db_index=True)
    key = models.CharField(max_length=200,db_index=True)
    value = models.CharField(max_length=1024)

class Event(models.Model):
    session = models.ForeignKey(Session,db_index=True)
    ts = models.BigIntegerField(db_index=True)
    category = models.CharField(max_length=200, db_index=True)
    action = models.TextField()
    label = models.TextField()
    value = models.TextField()

recordtrace/views.py
import json, logging, csv
import base64

from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.template.defaultfilters import slugify

from recordtrace.models import Session, Event, Metadata

#from django.utils.six.moves import range
from django.http import StreamingHttpResponse



#logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
logger = logging.getLogger(__name__)


class Echo(object):
    #"""An object that implements just the write method of the file-like
    #interface.
    #"""
    def write(self, value):
        #"""Write the value by returning it, instead of storing in a buffer."""
        return value


# def sortAndUniq(input):
#   output = []
#   for x in input:
#     if x.doc_url not in output:
#       output.append(x)
#   output.sort()
#   return output




@login_required
def index(request):
    latest_session_list = Session.objects.all().order_by('-date')

    context = { 'sessions': latest_session_list }
    return render(request, 'recordtrace/index.html', context)

@login_required
def projects(request):
    projs = Session.objects.values('doc_url').distinct()

    for pr in projs:
        pr['people_count'] = Session.objects.filter(doc_url = pr['doc_url']).values('session').distinct().count()

    projs.order_by('-people_count')

    context = { 'sessions': projs }
    return render(request, 'recordtrace/project.html', context)

@login_required
def temp_projects(request):
    uuids = Session.objects.order_by('-date')

    paginator = Paginator(uuids, 25) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        sessions = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        sessions = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        sessions = paginator.page(paginator.num_pages)

    context = { 'sessions': sessions }
    return render(request, 'recordtrace/temp_page.html', context)



@login_required
def connections(request,session_doc_url):
    session_doc_url = base64.b64decode(session_doc_url)
    latest_session_list = Session.objects.filter(doc_url=session_doc_url).order_by('-date').values('session','id','doc_url')
    sessions_total = Session.objects.filter(doc_url=session_doc_url)

    for pr in latest_session_list:
        pr['count_sessions'] = Event.objects.filter(session_id = pr['id']).filter(action = 'browser').count()
        pr['count_events'] = Event.objects.filter(session__session = pr['session']).count()
        pr['user_events'] = Event.objects.filter(session__session = pr['session']).filter(category = '_user').count()
        pr['system_events'] = Event.objects.filter(session__session = pr['session']).filter(category = '_system').count()

    paginator = Paginator(latest_session_list, 25) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        sessions = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        sessions = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        sessions = paginator.page(paginator.num_pages)
    # IF THE PAGINATOR IS NEEDED
    #context = { 'sessions': session, 'docurl': session_doc_url }
    context = { 'sessions': sessions, 'docurl': session_doc_url, 'vis_data': sessions_total }
    #context = { 'sessions': latest_session_list, 'docurl': session_doc_url, 'vis_data': sessions_total }
    return render(request, 'recordtrace/people.html', context)


@login_required
def session(request,uuid):
    session = Session.objects.get(session=uuid)
    latest_event_list = Event.objects.filter(session=session).order_by('ts')
    context = { 'session': session }
    return render(request, 'recordtrace/session.html', context)


#@login_required
#def unique_session(request,uuid):
#def session(request,uuid):
    #session = Session.objects.get(session=uuid)
    #latest_event_list = Event.objects.filter(session=session).order_by('ts')
    #context = { 'latest_event_list': latest_event_list, 'session': session}
    #return render(request, 'recordtrace/unique_session.html', context)
#    return HttpResponse("Hello, world. You're at the recordtrace session %s." % session_id)

@login_required
def unique_session(request,uuid,proj_url):
    proj_url = base64.b64decode(proj_url)
    session = Session.objects.get(session=uuid)
    latest_event_list = Event.objects.filter(session=session).order_by('ts')
    context = { 'latest_event_list': latest_event_list, 'session': session, "docurl": proj_url, "uuid": uuid }
    return render(request, 'recordtrace/unique_session.html', context)



@login_required
def all_connections(request):
    people = Session.objects.values('session').distinct()

    for pr in people:
        pr['people_count'] = Session.objects.filter(session = pr['session']).count()

    projs.order_by('-people_count')

    context = { 'sessions': projs }
    return render(request, 'recordtrace/project.html', context)




@login_required
def unique_session_table(request,session_id):
    session = Session.objects.get(id=session_id)
    context = { 'session': session }
    return render(request, 'recordtrace/unique_session_ref.html', context)


@login_required
def sessionvis(request,session_id):
    session = Session.objects.get(id=session_id)
    context = { 'session': session }
    return render(request, 'recordtrace/sessionvis.html', context)

@login_required
def showJSON(request,session_id):
    session = Session.objects.get(id=session_id)
    context = { 'session': session }
    return render(request, 'recordtrace/json.html', context)

@login_required
def showProjJSON(request,proj_url):
    session = Session.objects.filter(doc_url=proj_url)
    context = { 'sessions': session }
    return render(request, 'recordtrace/projJson.html', context)

@login_required
def showProjCSV(request,proj_url):
    session = Session.objects.filter(doc_url=proj_url)
    context = { 'sessions': session }
    return render(request, 'recordtrace/projCsv.html', context)




@login_required
def showCSV(request,session_id):
    session = Session.objects.get(id=session_id)
    context = { 'session': session }
    return render(request, 'recordtrace/csv.html', context)


@login_required
def sessionJSON(request,session_id):
    session = Session.objects.get(id=session_id)
    latest_event_list = Event.objects.filter(session=session).order_by('ts')
    out = [ { 'ts': o.ts, 'cat': o.category, 'action': o.action, 'label': o.label, 'value': o.value, 'uuid': o.session.session } for o in latest_event_list ]
    output = json.dumps(out)
    return HttpResponse(output, "content_type='text/json'")
#    context = { 'latest_event_list': latest_event_list, 'session': session}
#    return render(request, 'recordtrace/session.html', context)

@login_required
def sessionVJSON(request,uuid):
    session = Session.objects.get(session=uuid)
    latest_event_list = Event.objects.filter(session=session).order_by('ts')
    out = [ { 'ts': o.ts, 'cat': o.category, 'action': o.action, 'label': o.label, 'value': o.value, 'uuid': o.session.session } for o in latest_event_list ]
    output = json.dumps(out)
    return HttpResponse(output, "content_type='text/json'")
#    context = { 'latest_event_list': latest_event_list, 'session': session}
#    return render(request, 'recordtrace/session.html', context)




@login_required
def projJSON(request,proj_url):
    proj_url = base64.b64decode(proj_url)
    #session = Session.objects.filter(id=session_id)
    latest_event_list = Event.objects.filter(session__doc_url=proj_url).order_by('ts')
    out = [ { 'ts': o.ts, 'cat': o.category, 'action': o.action, 'label': o.label, 'value': o.value, 'uuid': o.session.session } for o in latest_event_list ]
    output = json.dumps(out)
    return HttpResponse(output, "content_type='text/json'")

@login_required
def projCSV(request,proj_url):
    #session = Session.objects.filter(id=session_id)
    latest_event_list = Event.objects.filter(session__doc_url=proj_url).order_by('ts')
    out = [ { 'ts': o.ts, 'cat': o.category, 'action': o.action, 'label': o.label, 'value': o.value, 'uuid': o.session.session } for o in latest_event_list ]
    output = json.dumps(out)
    return HttpResponse(output, "content_type='text/json'")

@login_required
def downloadCSV(request,session_id,fileds=None):
    session = Session.objects.get(id=session_id)
    latest_event_list = Event.objects.filter(session=session).order_by('ts')
    #context = { 'session': session }
    # Create the HttpResponse object with the appropriate CSV header.
    #response = HttpResponse(content_type='text/csv')
    #response['Content-Disposition'] = 'attachment; filename=user_%s.csv' % slugify(session_id)

    #writer = csv.writer(response)
    headers = ["user","uuid","ts","category","action","label","value"]
    #writer.writerow(headers)

    rows = []
    rows.append(headers)

    for obj in latest_event_list:
        row = []
        #for element in headers:
            #row.append(element)
        for field in headers:
            if field in headers:
                if field == "uuid":
                    val = getattr(obj.session, "session")
                elif field == "user":
                    val = getattr(obj.session, "id")
                else:
                    val = getattr(obj, field)
                    #print str(val).encode('utf-8')
                    if callable(val):
                        val = val()

                    #val = "Django"
                #val = str(val).encode("utf-8")                    
                #row.append(str(val).decode('utf-8'))
                row.append(val)
        rows.append(row)

recordtrace/templates/recordtrace/people.html
{% extends "base.html" %}

{% load staticfiles %}
{% load recordtrace_xtras %}

{% block header %}<a href="{% url 'recordtrace:index' %}">Home</a> › <a href="{% url 'recordtrace:projects' %}">Projects</a> › <a href="{{ docurl }}" target="_blank">{{ docurl }}</a> › User Activity{% endblock %} 



{% url 'recordtrace:projJSON' docurl as the_JSON_url %}


{% block buttons %}
    <!--
    <div class='btn-group' style='margin-bottom:20px;'>
        <div class='btn disabled'><i class="icon-eye-open"></i> Explore</div>
        <div class='btn'>
            <a href="{% url 'recordtrace:projJSON' docurl %}" target="_blank">
                <i class="icon-download"></i> JSON 
            </a>
        </div>
        <div class='btn'>
            <a href="{% url 'recordtrace:projCSV' docurl %}" target="_blank">
                <i class="icon-download"></i> CSV
            </a>
        </div>
    </div>
    -->
{% endblock %}


{% block content %}
<!-- RESET HERE
<div id="viz"></div>
-->
       

    {% block thead %}

    <!-- full_csv HERE -->
    {% url 'recordtrace:downloadFULLCSV' docurl|base64_encode as full_csv %}

    <table class="table table-hover table-condensed">
        <thead>
            <tr>
                <th>Individual Browser Connections (UUId)</th>
                <th>User Id</th>
                <th class="sortable"><i class="icon-minus"></i> Total Sessions #</th>
                <th class="sortable"><i class="icon-minus"></i> Total Traces #</th>
                <th class="sortable"><i class="icon-minus"></i> User Traces #</th>
                <th class="sortable"><i class="icon-minus"></i> System Traces #</th>
                <th>Download—<i class="icon-download"></i> <a href="{{ full_csv }}">ALL (CSV)</a></th>
            </tr>
        </thead>
        <tbody>

    {% endblock %}





<!-- GENERATE THE TABLE -->
{% if sessions %}


    {% for session in sessions %}
        {% if session.count_sessions < 1 %}
            {% url 'recordtrace:session' session.session as the_url %}
        {% else %}
            {% url 'recordtrace:unique_session' uuid=session.session  proj_url=session.doc_url|base64_encode as the_url %} 
            {# {% url 'recordtrace:sessionvis' session.id as the_url %} #}

        {% endif %}

        <tr class="noshow">
            <td class="main-td" onmouseover="highlight('{{ session.session }}')" onmouseout="dimm('{{ session.session }}')"><a href="{{ the_url }}">{{ session.session }}</a></td>
            <td onmouseover="highlight('{{ session.session }}')" onmouseout="dimm('{{ session.session }}')">{{ session.id }}</td>
            <td onmouseover="highlight('{{ session.session }}')" onmouseout="dimm('{{ session.session }}')"><span class="text-error">{{ session.count_sessions }}</span></td>
            <td onmouseover="highlight('{{ session.session }}')" onmouseout="dimm('{{ session.session }}')"><span class="text-error">{{ session.count_events }}</span></td>
            <td onmouseover="highlight('{{ session.session }}')" onmouseout="dimm('{{ session.session }}')"><span class="text-error">{{ session.user_events }}</span></td>
            <td onmouseover="highlight('{{ session.session }}')" onmouseout="dimm('{{ session.session }}')"><span class="text-error">{{ session.system_events }}</span></td>
            <td onmouseover="highlight('{{ session.session }}')" onmouseout="dimm('{{ session.session }}')"><i class="icon-download"></i> <a href="{% url 'recordtrace:downloadCSV' session.id %}" target="_blank">CSV</a> | <a href="{% url 'recordtrace:downloadJSON' session.id %}" target="_blank">JSON</a></td>
        </tr>




    {% endfor %}
{% else %}
    <tr>
        <td colspan="7">No sessions are available.</td>
    </tr>
{% endif %}

        </tbody>
    </table>

    <script type="text/javascript">

        var _nodeList = Array.prototype.slice.call(d3.select("thead tr").node().children);

        var tables = document.getElementsByTagName('table');
        var table = tables[tables.length -1];
        var rows = table.rows;
        for(var i = 0, td; i < rows.length; i++){
            if(i!==0){
                td = document.createElement('td');
                td.appendChild(document.createTextNode(i));
                rows[i].insertBefore(td, rows[i].firstChild);
            }else{
                th = document.createElement('th');
                th.appendChild(document.createTextNode('#'));
                rows[i].insertBefore(th, rows[i].firstChild);
            }
        };

        d3.selectAll(".main-td")
        .each(function(){
            var _url = d3.select(this).select("a").html();
            var _url1 = _url.split("://")[1];
            var _data = _url.replace(/([.*+?^=!:${}()|\[\]\/\\])/g," ");
            _data = _data.toLowerCase();
            _data = _data.split(" ");

            d3.select(this.parentNode).datum(_data);
        });

        d3.selectAll(".sortable")
        .on("mouseover",function(){
            var _sel = d3.select(this),
                _i = _sel.select("i");
            if(_i.classed("icon-minus") == true){
                _sel.style("cursor","s-resize");
            }else if(_i.classed("icon-chevron-down") == true){
                _sel.style("cursor","n-resize");
            }else{
                _sel.style("cursor","row-resize");
            };
        })
        .on("mouseup",function(){

            var _sel = d3.select(this),
                _i = _sel.select("i"),
                _idx = _nodeList.indexOf(_sel.node()) + 1;

            var _tbody = d3.select(this.parentNode.parentNode.parentNode).select("tbody").node();
            if(_i.classed("icon-minus") == true){
                sort_table(_tbody,_idx,true);

                d3.selectAll(".sortable:not(.temp)")
                .select("i")
                .attr("class","icon-minus");

                _i.attr("class","icon-chevron-down");
            }else if(_i.classed("icon-chevron-down") == true){
                sort_table(_tbody,_idx,false);

                d3.selectAll(".sortable:not(.temp)")
                .select("i")
                .attr("class","icon-minus");

                _i.attr("class","icon-chevron-up");
            }else{
                sort_table(_tbody,0,true); 

                d3.selectAll(".sortable:not(.temp)")
                .select("i")
                .attr("class","icon-minus");

                _i.attr("class","icon-minus");
            };

            return null;
        });

    </script>


    <div class="pagination">
        <span class="step-links">
            {% if sessions.has_previous %}
                <a href="?page={{ sessions.previous_page_number }}">‹ previous</a>
            {% endif %}

            <span class="current">
                Page {{ sessions.number }} of {{ sessions.paginator.num_pages }}.
            </span>

            {% if sessions.has_next %}
                <a href="?page={{ sessions.next_page_number }}">next ›</a>
            {% endif %}
        </span>
    </div>


<!-- VISUALIZATION STUFF -->

<!-- GENERATE THE VISUALIZATION -->
<script src="{% static 'recordtrace/projvis.js' %}"></script>

<script type="text/javascript">
    function setProgress(){
        // MORE INFO AT https://gist.github.com/mbostock/3750941
        var meter = svg.append("g")
            .attr("class", "progress-meter")
            .attr("transform", "translate(" + w / 2 + "," + h / 2 + ")");

        meter.append("image")
            .attr("width",300)
            .attr("height",215)
            .attr("x",-300/2)
            .attr("y",-215/2)
            .attr("xlink:xlink:href","{% static 'recordtrace/progress.gif' %}")
         
        var text = meter.append("text")
            .attr("text-anchor", "middle")
            .attr("dy", ".35em")
            .attr("y",40)
            .text("Please wait as this may take a while.")
    };

    // THIS IS WHAT NEEDS TO BE RESET
    /*setProgress();
    d3.json("{% url 'recordtrace:projDJSON' docurl|base64_encode %}",visualizeSession);*/
    


    /*d3.json("{% url 'recordtrace:projDJSON' docurl|base64_encode %}")
    .on("progress", setProgress)
    .on("load", function(json) { visualizeSession(json) })
    .on("error", function(error) { console.log("failure!", error); })
    .get();*/
    function highlight(what){
        var color = d3.scale.category20b(),
            _session_num = new Array();

        what = what.replace(/\W/g, '').toLowerCase();
        d3.selectAll("rect.u-" + what)
            .each(function(d,i){
                var _sel = d3.select(this),
                    _sess = d.sessionID - 1;
                if(_sel.classed("end-point") === false){
                    _sel.style("fill",function(){
                        //return d3.rgb("#0088CC").brighter(_sess/5);
                        return color(d.sessionID);
                    })
                    .style("opacity",0.75);
                }else if(_sel.classed("end-point") === true){
                    _sel.style("fill",function(){
                        return "firebrick";
                    })
                    .style("opacity",0.75);

                    var _selX = _sel.attr("x"),
                        _t = d3.transform(_sel.attr("transform")),
                        _x = _t.translate[0],
                        _y = _t.translate[1],
                        _offX = +_selX + +_x;

                    svg.append("rect")
                        .attr("class","end-txt")
                        .attr("x",_offX - 3)
                        .attr("y",_activityHeight + margin.bottom + margin.top - 14)
                        .attr("width",80)
                        .attr("height",14)
                        .style("fill","#FFF");

                    svg.append("text")
                        .attr("class","end-txt")
                        .attr("x",_offX)
                        .attr("y",_activityHeight + margin.bottom + margin.top - 3)
                        .attr("text-anchor",function(){
                            if(_offX > w/2){
                                return "end";
                            }else{
                                return "start";
                            };
                        })
                        .text("End Session: " + (d.sessionID + 1) )
                        .style("font-size","11px");
                };

                if(_session_num.indexOf(d.sessionID) === -1){
                    _session_num.push(d.sessionID);
                }

                return null;
            })
            .moveToFront();

        d3.selectAll(".point:not(.u-" + what + ")")
            .style("opacity",0.1);

        var _legend = d3.select(".legend").select("p");

        _session_num.forEach(function(d){
            _legend.append("span")
                .html("&#x258e;session&nbsp;" + (d+1) + " ")
                .style("color",color(d))
                .style("margin-right","15px");
            return null;
        });

        return null;
    };
    function dimm(what){
        what = what.replace(/\W/g, '').toLowerCase();
        d3.selectAll("rect.u-" + what)
            .style("fill",null);
        d3.selectAll(".point")
            .style("opacity",0.5);
        d3.selectAll(".end-point")
            .style("opacity",0);
        d3.selectAll(".end-txt")
            .remove();

        var _legend = d3.select(".legend p").selectAll("span").remove();
        return null;
    }


</script>

{% endblock %}

recordtrace/templates/recordtrace/ref.html
{% extends "base.html" %}

{% block title %}Particpants{% endblock %}

{% block content %}
{% if sessions %}
    <ol start="{{ sessions.start_index }}">
    {% for session in sessions %}
        <li>
      <a href="{% url 'recordtrace:sessionvis' session.id %}">Vis</a>
	  <a href="{% url 'recordtrace:session' session.id %}">{{ session.session }}, {{ session.count_sessions }}, {{ session.doc_url }}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <p>No sessions are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if sessions.has_previous %}
            <a href="?page={{ sessions.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ sessions.number }} of {{ sessions.paginator.num_pages }}.
        </span>

        {% if sessions.has_next %}
            <a href="?page={{ sessions.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endblock %}

recordtrace/templates/recordtrace/session.html
{% extends "base.html" %}

{% load staticfiles %}
{% load recordtrace_xtras %}

{% block header %}<a href="{% url 'recordtrace:index' %}">Home</a> › <a href="{% url 'recordtrace:projects' %}">Projects</a> › <b>Sessions</b>{% endblock %}


{% block content %}
<p><a href="{% url 'recordtrace:index' %}">Back to Index</a>
{% if latest_event_list %}
    <ol>
    {% for event in latest_event_list %}
        <li><a href="{% url 'recordtrace:event' event.id %}">{{ event.session.session }}, {{ event.ts }}, {{ evet.category }}, {{ event.action }}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <p>No events are available.</p>
{% endif %}
{% endblock %}

recordtrace/templates/recordtrace/temp_page.html
{% extends "base.html" %}

{% load staticfiles %}
{% load recordtrace_xtras %}

{% block header %}<a href="{% url 'recordtrace:index' %}">Home</a> › Temp{% endblock %}

{% block content %}

    <table class="table table-hover table-condensed">
        <thead>
            <tr>
                <th>UUID</th>
                <th>URL</th>
                <th>Date</th>
                <th>Download (Single File)</th>
            </tr>
        </thead>
        <tbody>

{% if sessions %}
    {% for session in sessions %}
        <!--url 'recordtrace:connections' session.doc_url|base64_encode as the_url-->
        {% url 'recordtrace:connections' session.doc_url|base64_encode as the_url %}
        {% url 'recordtrace:downloadFULLCSV' session.doc_url|base64_encode as full_csv %}
        {% url 'recordtrace:downloadFULLJSON' session.doc_url|base64_encode as full_json %}

        {% url 'recordtrace:csv' session.id as the_session_url %}
    <script type="text/javascript">
        console.log("{{ session.id }}")
    </script>

        <tr class="noshow">
            <td class="main-td"><a href="{{ the_session_url }}" target="_blank">{{ session.session }}</a></td>
            <td><a href="{{ the_url }}">{{ session.doc_url }}</a></td>
            <td>{{ session.date }}</td>
            <td><i class="icon-download"></i> <a href="{% url 'recordtrace:downloadCSV' session.id %}" target="_blank">CSV</a> | <a href="{% url 'recordtrace:downloadJSON' session.id %}" target="_blank">JSON</a></td>
        </tr>

    {% endfor %}  
{% else %}
    <tr>
        <td colspan="7">No sessions are available.</td>
    </tr>
{% endif %}
    
        </tbody>
    </table>

    <script type="text/javascript">

        var _nodeList = Array.prototype.slice.call(d3.select("thead tr").node().children);

        var tables = document.getElementsByTagName('table');
        var table = tables[tables.length -1];
        var rows = table.rows;
        for(var i = 0, td; i < rows.length; i++){
            if(i!==0){
                td = document.createElement('td');
                td.appendChild(document.createTextNode(i));
                rows[i].insertBefore(td, rows[i].firstChild);
            }else{
                th = document.createElement('th');
                th.appendChild(document.createTextNode('#'));
                rows[i].insertBefore(th, rows[i].firstChild);
            }
        };


    </script>


    <div class="pagination">
        <span class="step-links">
            {% if sessions.has_previous %}
                <a href="?page={{ sessions.previous_page_number }}">‹ previous</a>
            {% endif %}

            <span class="current">
                Page {{ sessions.number }} of {{ sessions.paginator.num_pages }}.
            </span>

            {% if sessions.has_next %}
                <a href="?page={{ sessions.next_page_number }}">next ›</a>
            {% endif %}
        </span>
    </div>


{% endblock %}